### ISSUE TITLE
Adjustable Power Supply broken

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#156]
1) please describe the problem:
https://wiki.comakingspace.de/Power_Supplies
The reverse Voltage protection didn´t work. @Johannes09 broke it, @Pakue95 said he will fix it.

**Comment by Pakue95** [comment]
I googled around a bit and found a thread of the same power supply with similar [issues](https://www.roboternetz.de/community/threads/70274-Schaltplan-für-Labornetzgerät-VOLTCRAFT-LPS-1305/page2).

It seems that T101 (PNP transistor BC856B), was damaged due to backwards power from a battery. I replace it with a 2N3906 which I had on hand. That seemed to have fixed the issue with the voltage control. Only the C-Limit LED seems to be a bit buggy, but that isn't a problem regarding functionality.

I need to replace the thermal compound once I bring the power supply back to the space.

**Comment by NitramLegov** [comment]
Läuft das eigentlich wieder? :)

**Comment by Johannes09** [comment]
Ja
