### ISSUE TITLE
Gehäuse für Prusa MK2S bauen

### ISSUE THREAD

**Issue by emka** [comakingspace/do-something#18]
Um Material wie ABS drucken zu können, wäre ein Gehäuse sehr praktisch.

**Comment by NitramLegov** [comment]
https://diebastelkammer.wordpress.com/2015/02/13/prusa-upgrade-teil-1-warm-vernetzt-und-full-metal/

Das sieht mir wie ein recht günstig zu bauendes Gehäuse aus. Ich glaube ich habe noch Siebdruckplatten, die man nutzen könnte.

Denke für die Scheibe kann man auch "Hobbyglas" aus dem Bauhaus nehmen (gibts in verschiedenen Größen, z.B. 50x50 mit 2mm dicke https://www.bauhaus.info/aluplatten-kunststoffplatten/hobbyglas-owocor/p/14211156)

Falls wir einen Lüfter brauchen: tut es da ein PC-Lüfter? Von denen hab ich noch einige daheim rumfahren...

**Comment by NitramLegov** [comment]
Question: Does the case for the printers need a filter? Does it need a fan?
For a Filter, I have 2 leftover filters from my kitchen hood (I bought them a while ago, but they have the wrong size).
If we need a fan, I have some computer fans left (are they enough?)
My proposal would still be to leverage the whole we already have in the wall and blow the air outside...

**Comment by NitramLegov** [comment]
Ich hab drei Siebdruckplatten mitgebracht und mal in die Holzwerkstatt gestellt. Die könnte man nutzen, um das Gehäuse zu bauen.

**Comment by NitramLegov** [comment]
Hat hier eigentlich noch jemand Interesse dran? Bisher hatte ich nicht den Eindruck, dass jemand ABS drucken will..

**Comment by LukasFreeze** [comment]
Ich würde bei solchen Sachen generell sagen dass es gut wäre, die Idee an
sich und ggf bisherige Diskussionen/Überlegungen an sinnvoller Stelle im
Wiki zu notieren, aber wenn am Issue ewig nichts gemacht wird lenkt es eher
nur von dringenderen Sachen ab...

**Comment by reogaro** [comment]
Lucas has offered to donate a large quantity of ABS 3D printing filament, and the issue of printing ABS and other high-temp/specialized filaments has come up on multiple occasions in the past. Since interest in a enclosed, ABS-capable 3D Printer has come up again I'm reopening this issue and am planning to finally build "the box".

The telegram chat has shown multiple makers are interested. High-temp (>300°C) printing requires a capable Hotend, a enclcosed print chamber and a air filter. Building a small box-frame printer (Voron 0, SnakeOilXY, Tiny-M) would make printing in winter time easier but will eat up at least 10x more time, money and effort. I'd be willing to build and tune a machine like this but don't have the money or parts.

I suggest we build a box and put a Prusa in it, since the i3 fleet is already there and well documented. IKEA table or welded steel as a frame and acrylic or wood panels make for a cheap and easy box. Filtering could be done using a [Nevermore](https://github.com/nevermore3d/Nevermore_Max) filtering system or something similar if that's enough, or using the laser cutter filtering system if the ~~safety nerds~~ safety experts object.

Some optional improvement ideas beyond "building a box":
- ABS frame parts to help the printer handle the heat
- Hardened nozzles for additives
- Chamber heater for wintertime
- Lights
- Insulation

If anyone else has more suggestions please post, I'm open to your ideas. I intend to go and measure the printer and print farm next wednsday and will start planning the box then.

**Comment by LukasFreeze** [comment]
Wenn wir das weiter verfolgen, werden die neuen Bambu-Drucker die naheliegendere Option sein :-)
