### ISSUE TITLE
Update Slic3r in Electronics Room

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#29]
The installation of Slic3r in the electronics room is version 1.33
The most current one is 1.40
It provides a couple of improvements in regards to handling different printers (Multi malterial extension, etc.) and settings.
Therefore, I think it should get upgraded. In principle, I can do it, but I don´t want to risk loosing any of the settings you have made.

**Comment by NitramLegov** [comment]
In addition, at least on windows, the new version also tells me the estimated printing time.

**Comment by LukasFreeze** [comment]
cool, built-in print time estimation was really missing so far!

I haven't saved any special settings myself but I believe @Pakue95 did some experiments with flexible filament and there should be "UniCoFil" profiles as well. Are they backed up somewhere? Otherwise I'd say we copy the current settings folder(s) to a safe location before updating and then we see whether they are kept or we have to re-import them.

**Comment by Pakue95** [comment]
Slic3r is updated to 1.40 and the old config was ported.
