### ISSUE TITLE
Workbee CNC (COMS00003) Broken controller

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#307]
The controller of the Workbee CNC has been having some issues lately with:
* loosing configurations (#303)
* randomly stopping during jobs

Which seems to boil down to a faulty controller board. 

The best course of action IMO is to replace the controller board + the CNCjs Pi with a single Duet board, as that can serve a web based UI standalone.

Possible boards:
* Duet3 6HC (250€)
* Duet3 5+ mini Wifi/Ethernet (150€)
* Duet2 Wifi/Ethernet

I'd go with one the Duet3 Ethernet boards as they are still in active feature development in RRF and can be hooked up to a Pi in case somebody wants to implement a gamepad controller. The 5+ mini has a little lower stepper current than the current controller (1.4A vs 1.75A RMS).

@reogaro and @Blacksheep70 agreed to tackle the conversion project and will send me a BOM once a plan has been made.

ToDo so far: 
* [x] rewire drag chains to allow the controller board to be mounted on the table instead of the X-axis
* [x] install controller board in dust proof box
* [x] configure controller board
* [x] update Wiki docu for the new controller board

Optionals:
* [x] @reogaro suggested getting a display ([PanelDue](https://www.filafarm.de/collections/duet3d/products/paneldue)) for the CNC
  * alternatively @Johannes09 offered a wall mount android tablet that can also run the web controller

**Comment by Blacksheep70** [comment]
@reogaro : Let me know if you have a task to complete

**Comment by reogaro** [comment]
Today, the planning has advanced further.

Motherboard: The workbee uses MT-2303HS280AW NEMA23 stepper motors which take up to 2.8A phase current, which would require a Duet 3 6HC to drive to their full potential. We should get that. And we're installing it on the X axis beam (read wiring section for why), but in an enclosure. Details on the enclosure aren't set yet, I am looking into it.

Wiring: Johannes has donated some 4-wire drag chain cables (6x 4m AWM E43868 20379 80C 30V VW-1 probably 0,14mm^2). Since these cables are quite thin, we can't move the controller off the X axis. Longer cables, same thickness -> more voltage drop, and we're quite close to the edge (back-of-the napkin math suggests more than 10% losses already), but mounting the motherboard on the X carriage will shorten the wire runs just enough to make them viable.

Endstops: There has been some discussion about adding positive and negative endstops, inductive endstops, and more. I'm making a call and putting a endstop to this discussion, if only to make that pun. We're keeping the current clicky switches, but will rearrange them to home to X- Y- instead of X+ Y+ to simplify the wire runs.

Crimping: It seems like the motors are using JST SM plugs. I will donate a set and lend my crimping tool. The Duet board uses Molex KK 254 plugs, maybe @Pakue95 has the plugs and crimping pliers required for that?

Tablet: Johannes has offered to donate his industrial tablet for the project. No PanelDUE required. Thank you!

Helpers: Jannek and Lennard have also offered to help, which is very much appreciated.

Drag Chains: We're gonna flip the Y Axis drag chain by 180° to have it end on the front of the machine. This will include designing a new mounting bracket, I'll do that.


Updated ToDo so far:

- [ ] Acquire Duet 3 6HC @Pakue95
- [ ] Acquire touch interface @Johannes09 
- [ ] Solve Molex crimping problem
- [ ] Find a dustproof mainboard mounting solution, or build one (I'm on it)
- [ ] Once the parts arrive, we can schedule a date to start working

**Comment by Pakue95** [comment]
I've got a crimping tool that works for the Molex KK 254 plugs, so that shouldn't be an issue. 

I'd honestly avoid using cables with such small diameter for running the steppers. Given that drag-chain Ölflex with 0.75mm2 costs [1.10€/m ](https://www.sorotec.de/shop/Steuerleitung-OeLFLEX--CLASSIC-110-4-x-0-75-mm-.html) (maybe shielded would be even better) I'd say that that's an unnecessary compromise. I'd rather have the controller board fixed to the table which avoids running an ethernet cable through the Y-chain and makes access to the controller board easier. 

The 0.14mm2 cables can still be used to run the end stops if we want to safe a little on buying cables.


Here is a case option for a duet 3 6hc: https://www.reichelt.de/alugehaeuse-1550-w-222-x-146-x-105-mm-aluminium-1550wh-p221425.html

**Comment by Pakue95** [comment]
The crimping connectors and boards are available now. I've ordered the 0.75mm2 cable (12m) but will order some more to be sure it is enough).
I've also gone ahead and ordered the aluminium case.

**Comment by reogaro** [comment]
Update on what has happened so far:

- All of the old wiring was removed
- The duet board has recieved its housing
- The new Y drag chain is installed with a custom steel mounting bracket
- a new mounting board for the reworked electronics is installed
- The rear left frame plate was replaced with a custom one to avoid colliding with the belt
- the carriage drag chain mount was replaced
- The safety box wiring was analyzed and a new plan is ready, though not made yet

Thanks to Luca, Patrick and Johannes who helped along the way. Progress is slow but steady.

**Comment by reogaro** [comment]
Update: Wiring is almost done and only needs some refinement (such as ethernet, e-stop and safety stuff). We're working on firmware config.

We need 3 or more network jacks at the CNC. Can we get a network switch or similar for this?

To check in the base config:
- Static IP
- Dual Y axis
- Directions (X is good, Y is good, Z- is currently up)
- Steps/mm
- Speed & Accel (XY is way too fast)
- Motor Currents (currently 2A)
- Spindle Config
- E-Stop Config

**Comment by NitramLegov** [comment]
Is there an option to use WiFi?

If not, we do have ethernet in the workshop. However, it is back at the wood lathes. So we would need to install an access point over there and then put a cable to the CNC router.

There should be an old Fritz!Box cable available at the space which just needs a new power supply :)

**Comment by NitramLegov** [comment]
One request regarding the config:
Please do not assign a static IP in the config of the CNC router. We assign static IPs in the router config, not in the client config :)

**Comment by NitramLegov** [comment]
The Router and the attached tablet are connected to the Network via Ethernet.

Fixed IP adresses are configured in the router and are documented in the wiki: https://wiki.comakingspace.de/Network

For the tablet, I have blocked the access to the Internet. 
@reogaro How do we get files onto the router? Would something like the file drop for the Laser Cutter make it more user-friendly?

**Comment by reogaro** [comment]
The router now works, it runs and mills parts. There's still some minor kinks to work out, arc moves cause weird jitter and the postprocessor isn't done yet.

And all the documentation has to be updated, including introductions and so on. I'm working on it with all the motivation I can muster for writing docs.

@NitramLegov
>@reogaro How do we get files onto the router? Would something like the file drop for the Laser Cutter make it more user-friendly?
The Duet controller Web interface allows manual uploads via a file selection menu through any network-connected device. A more sophisticated solution would require a PC such as Raspberry Pi, which adds complexity. The juce isn't worth the squeeze IMO.

**Comment by reogaro** [comment]
Yes, if it uses the existing hardware I'm all for it.

Today I have milled more test pieces (anybody need a MK3S Frame from 10mm Plywood? Seriously.) and fine-tuned the RRF and Fusion 360 configuration files. We're entering the final stretch.

**Comment by reogaro** [comment]
# The WorkBee CNC is almost ready!

The Wiki Documentation has been expanded - Head over to https://wiki.comakingspace.de/WorkBee to familiarize yourself with the machine and its processes. Feel free to proofread and let us know if anything seems missing.

While the machine is fully functional, we'd appreciate your help in making it even better for everyone. Here's a list of quick and easy tasks anyone can tackle today:

- [ ] Vacuum the sawdust everywhere
- [ ] empty the dust separator
- [ ] empty the shopvac
- [ ] Swap out the yellow Ethernet cable from the switch to the tablet with the proper length white one on top of the CNC
- [ ] cable manage below the desk with zip ties
- [ ] Cable manage from the desk to the wall
- [ ] Buy hooks for the pegboard wall (Küpper 72000 at Bauhaus) and hang the dust shoes
- [ ] 3D Print this hillarious endmill disposal bin: https://www.printables.com/model/451060

We just need to finish the commissioning process and the WorkBee will be open to the public again!

**Comment by NitramLegov** [comment]
@reogaro @Johannes09 Is this done? Is anything left open here? :) The wiki says that the CNC Router is back in action...

**Comment by Johannes09** [comment]
CNC Router is back in action
