### ISSUE TITLE
Process around non-inventoried tools

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#42]
As far as I know, we have quite a few non inventoried tools (routers, bandsaws, etc.)
Some of them seem to be broken / faulty, some seem to be okay and just need inventorization
Do we have some kind of process around these? Maybe a small checklist?
E.g.
- [x] Name the tool
- [x] Take a picture
- [x] Document it in the wiki (status: pre-commissioning)
- [x] Create / check the introduction in the wiki
- [x] Security check (loose cables, etc.) - done or witnessed by a manager
- [x] Test it - done or witnessed by a tutor or a manager
- [x] Have a manager make the tool available (physically and changing the status in the wiki)

**Comment by LukasFreeze** [comment]
You're right, the process for these could probably be clearer :-P

The two main issues with every new tool are safety and documentation, and we are trying to get to the point where only fully commissioned tools are in the public rooms - that's why some are locked away for now. There are still some tools out in the open missing some important steps though, for example the lathes (#4 & #7) and some that don't even have "issues" yet...

I like your idea of a checklist and would add some important details:
- one of the managers needs to do (or witness) the security check and make the final "availability" decision so the gGmbH is responsible, and not any single person
- testing of the tool needs to be done under supervision of an experienced tutor or (in case where we haven't defined an introduction yet) a manager
- **before** a new type of tool is added to the selection, we should (at least start to) write an introduction page for it
- for the "inventorization" itself (non-public, needed mostly for insurance), we need a tool's **name, owner and approx. value** 

Any other opinions?

**Comment by NitramLegov** [comment]
I updated the list with your comments. The only thing I am not sure about is how to integrate the last point (maybe that should be part of the last step to be done by the management)

**Comment by NitramLegov** [comment]
Ich hab mal angefangen, ein (Template) [https://wiki.comakingspace.de/Template:Commissioning] zu erstellen, das man in die jeweilige Wiki-Seite einfügen kann.
Damit kann man den Leuten eine einfach "todo" an die Hand geben, die entsprechend abgearbeitet werden kann. Ist noch nicht perfekt, aber ein starting point.

**Comment by NitramLegov** [comment]
Das Template fügt übrigens auch eine neue Kategorie [Comissioning](https://wiki.comakingspace.de/Category:Commissioning) hinzu, die man nutzen kann, um eben diese Geräte zu tracken. Vielleicht ist das auch was als neuer Link für das Readme?

**Comment by LukasFreeze** [comment]
Das Template funktioniert bisher schonmal ganz gut! Link ist jetzt im Readme :-)

**Comment by NitramLegov** [comment]
Dann mach ich hier mal zu. Für Anpassungen am Template brauchen wir kan kein Issue mehr ^^
Und wieder aufmachen geht ja immer ;)
