### ISSUE TITLE
Promote collaboration possibilities

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#43]
This issue is just intended to serve as a discussion point. Right now, not a lot of members are actively participating in our issue list or our wiki. Last week, we had 5 unique visitors on the issue list. 
When talking to members at the space, some were not even really aware how the issue list works (a question was e.g. "so who adds stuff to that list?") 
Therefore, I would think we should discuss measures to promote the list and to motivate people to participate in improving the space.
I know we discussed some of these things in person already, so this list should just serve as a starting and documentation point:
- Are people (especially non-developers) "scared" of github (since they never used it / have no account)?
- Post new issues on the Mailing list (are people reading the ML?)
- Start do-something hours (open hours without supervision / tutoring for working on issues)
- Wiki-seminar (done by Lukas?)
- Instead of marking things with "#": putting a QR-Code to faulty tools?
- promoting activities that really helped the space in whatsapp or the ML ("xyz took up issue 123, now he have a new tool abc available") - in order to have people see the benefits of this.

Let´s discuss

**Comment by LukasFreeze** [comment]
Interesting, I didn't know awareness about this tracker was that low :-/

I'll be in again tomorrow evening and would like to test the concept of a "do-something hour" from 22:00 to 23:00, but when possible we should have some of those on their own (e.g. a Saturday, depends on supervisor's availability of course...) to increase visibility. I could imagine there are many members who would like to help in a team but are not yet confident to try something on their own.

I'm not sure yet when I can hold a little wiki seminar but have been preparing it on the side - hopefully sometime soon :-)

Your points about the mailing list are great, we've posted breakthroughs on some of the "issues" there in the past but not since you joined it seems...so that may need to happen more often ;-)

Finally, I don't think replacing the "#" labels with QR codes is a good idea as it adds an extra level of difficulty to opening every single issue. Perhaps rather a general code leading to the tracker as a whole, if that helps people? We could make more signs similar to the one in the hallway and add the code to those (e.g. on the repair shelf #38)

**Comment by NitramLegov** [comment]
For the "do-something hours", I would love to throw in the idea of using the SpaceAPI again in order to publicly show the space as open - but with a clear indication that it is a do-something hour. Also, I think for most users you would need to define, what "do-something" exactly means (e.g. basic members are supposed to only work on things for the space, no personal projects). 

Regarding the QR-Code idea, I agree to you as in it doesn´t make sense to replace the current # labels with it or to make it mandatory. I like the idea of having some more central things (like the repair shelf you mentioned) being exptended with a QR Code (wherever it should target to). In general, this should be a help for people trying to understand an issue, not an additional adminitrative step preventing people from opening an issue. I´ll prepare something at least for the repair shelf tomorrow.

**Comment by NitramLegov** [comment]
The new "Help the space" printouts can be found on github:
https://github.com/comakingspace/CommonFiles/blob/master/Printouts/Help%20the%20space.docx

You can manually write your issue number on it. The QR-Code links to the overall issue tracker.

**Comment by LukasFreeze** [comment]
a few improvements from my side:
- made "task list" more visible in Readme.md
-- also moved the German version to the top of the document as most users/members will prefer that language
- linked "Help the space" signs in wiki & Readme
- introduced three more members to the whole "issue tracking" process this week

**Comment by LukasFreeze** [comment]
I think writing to the mailing list about important progress, asking for help etc is a good idea and worth the extra effort as long as "issue tracker awareness" is still low.

Just did that for #23 and #45 :-)

**Comment by NitramLegov** [comment]
I think we are making some progress here, but can still improve further.
Therefore, Let´s use this issue in order to discuss the idea of a members meeting, which could be a platform for discussing ideas and further collaboration possibilities. I know the barbeque evenings were supposed to serve as such a discussion forum, but that didn´t really work out. My theory is that people were just not aware of these evening serving such a purpose.

Therefore, my proposal would be the following steps:

1. discuss the general idea in this issue
2. put together a rough list of topics. Maybe the following can serve as a starting point:
2.1 (Quick) Statistics about the space [money? member count? recent activities and their success]
2.2 New things in the space (new tools, implemented projects, etc.)
2.3 Collaboration possibilities (Issue tracker, wiki, do-something hours, ongoing projects [like the shredder])
2.4 Seminar Idea gathering (topics, members willing to present)
2.5 Birthday planning (if this happens early enough)
2.6 Feedback on recent activities (concert, barbeque evenings)
2.7 Open discussion round for further improvement ideas
3. Propose it on the Mailing List and in the whatsapp group - as a first test run of how interested people are in something like this


What do you think?

**Comment by emka** [comment]
These are great suggestions, thanks! We already talked a bit in person about it.
How about setting up a doodle to find a date that suits as many members as possible?

**Comment by NitramLegov** [comment]
I created a Doodle:
https://doodle.com/poll/gmsei6gnt7u49f7y

it currently contains options for the next couple of weekends after our birthday party. In case you want me to add options, please let me know.
If you´re fine with the options, I would promote it on the Mailing List as well as in WhatsApp.

**Comment by LukasFreeze** [comment]
Weekends are going to be hard, Mitja suggested today that we just have it
on a suitable Wednesday or Friday after 8?

So please include some weekday options :-)

**Comment by NitramLegov** [comment]
Since you mentioned Weekends to be hard, I kicked them out entirely 😉

The poll now includes Wednesdays and Fridays until end of November.

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Lukas <notifications@github.com>
Gesendet: Tuesday, September 11, 2018 8:37:48 PM
An: comakingspace/do-something
Cc: NitramLegov; Author
Betreff: Re: [comakingspace/do-something] Promote collaboration possibilities (#43)

Weekends are going to be hard, Mitja suggested today that we just have it
on a suitable Wednesday or Friday after 8?

So please include some weekday options :-)

**Comment by NitramLegov** [comment]
@beanobeano also mentioned that we could plan a "mini-hackathon" in order to emphasize working on the commissioning of new tools.

I would love something like that taking place on some weekend :)

**Comment by NitramLegov** [comment]
# Adopting a Workshop-corner
When talking to the DingFabrik in Cologne, they mentioned the idea of people "adopting" a corner / part of the Workshop. Adopting in this case means to be responsible for the corner. People that take over parenthood would be able to introduce their own system of ordering and make changes to the corner. They would also be able to enforce it (tell people that didn´t clean up properly how to do it, etc.). However, they are responsible for the area to be tidy. So if push comes to shove, they would need to clean it up.
In general I would say we should always have 2 people adopting a corner.
Talking to @emka and @LukasFreeze sounded like they are in favor of this idea.
I ran this Idea through @Johannes09 as well real quick and he sounded interested in taking over responsibility for the electronics workbench.
**Therefore, my proposal would be to start this concept with the electronics workbench and find a parnet for @Johannes09 **

# The Members Meeting ("Plenum"?)
The Doodle in here did not receive a lot of attention. Honestly, I was hoping at least for the people that are active on github to participate in the doodle. After that I would have gone out to all the other Members with a streamlined list of possible dates. However, this plan obviously did not work out.

Therefore, my proposal is now the following:
**Let´s have bi-weekly members meetings starting next week Friday (5th October)**
We should have regular members meetings in order to get everybody up to speed. In order to get as many members as possible, I would propose to have them alternating on Wednesdays and Fridays.
For this, we should stop the "Making hours" at around 8 pm (at least for the first two ones) and then start the Plenum. 
_Organisation / Expectations_
If nothing speaks against it, I would hope for some support from our management. This would include putting it into the calendar and starting the session. If you want me to, I can take over the promotion via the mailing list and hang up something in the space.
Since the space is open tomorrow evening, I would think that we can also have a quick personal discussion about this tomorrow. In regards to this issue, I would say if there are no other comments until Monday, this proposal is accepted and we will run it as proposed ;)

**Comment by LukasFreeze** [comment]
Did you get to discuss any of this on Friday? Here are my two cents:

- adopted areas: I like it! But it is important in my opinion that the people responsible ("area patrons?") do not have to clean up if nobody else does, they should just work out solutions that make it simple for everyone to keep order. For example, the electronics workbench urgently needs some system/labeling regarding its drawers but then everyone should clean up... if everything is messy and a patron does clean up, a strongly worded eMail or conversation would definitely be justified. Otherwise I'm afraid there is actually going to be a reduced awareness of every member's own cleaning duties except in areas where the patrons happen to be able to invest a lot of time supervising.

- plenum: Also totally in favor! But once a month would be enough in my opinion, and from 9 instead of 8 pm. We can still increase frequency or duration once it's established, but I'm against blocking a bunch of time on a regular basis right from the start. With fewer meetings, each one becomes more important and interested members could actually block that time and make sure they can attend. I think it is also important to give a voice to those who can't attend, e.g. by posting topics/open questions beforehand. That is also much easier if the meetings are not too close together...

So far from my side, what does everyone else think?

**Comment by emka** [comment]
Monthly sounds more realistic to me as well. Of course the "area patrons" shouldn't clean up all the time, but make sure everyone cleans up after himself instead.

Thanks for sending out the invitiation @NitramLegov! I would be glad to read a summary of the discussions on the mailing list because I can not attend this Friday. Looking forward to new ideas.

**Comment by NitramLegov** [comment]
Yes, of course. 
I just created a basic structure in the wiki to keep track of anything regarding the [plenum](https://wiki.comakingspace.de/Plenum).
The meeting minutes can be found in there. Of course, after the plenum, they should also get send out via the mailing list.

This was inspired by what the [RZL](https://wiki.raumzeitlabor.de/wiki/Plenum) and the [Wikimedia Search Team](https://www.mediawiki.org/wiki/Wikimedia_Search_Team/Meeting_minutes) do.

**Comment by NitramLegov** [comment]
Just to keep the issue up to date as well:
We had our first plenum yesterday and I would say it went really well! We had 14 members and 2 managers attending the meeting, which shows that there is quite some interest in the community for this format :)
The discussions went really well and we already decided a few new things (area patrons, picture wall, project board). The Minutes can be found in the wiki: https://wiki.comakingspace.de/Plenum/Meeting_minutes/2018-10-05

**Comment by NitramLegov** [comment]
I think interested people are aware of what can be done at the space and the community is getting stronger and stronger.
For any further actions or proposals We have the Plenum now. In case an issue is needed for specific actions, I would recommend opening a new one :)
