### ISSUE TITLE
Make the spindle speed controllable

### ISSUE THREAD

**Issue by Chris0812** [comakingspace/do-something#63]
In order to mill Aluminum with our Workbee, we'll need a spindle capable of rotating as slow as 6000 RPM - our current one goes 16000 and higher. Donations are very welcome, to get the ~100€

**Comment by NitramLegov** [comment]
Do you have anything specific in mind? In case we get a new router, I would say we should invest in one which allows the speed to be controlled by the CNC Router itself, so that you can just set the speed in your CAM Software. From what the [description](https://openbuildspartstore.com/cnc-xpro-v3-controller-stepper-driver/) of the controller board (I hope this is the right one) says, the board is capable of "Spindle Direction and PWM Control output"

This might also add the advantage of being able to stop the router when pressing the E-Stop

**Comment by Pakue95** [comment]
I don't think 100€ is enough for a spindle and a VFD. Also keep in mind there this isn't going a plug&play solution for our router (at least not with our controller board).

The WorkBee CNC its still a router and **not** a milling machine therefore simply having a lower spindle speed won't fix the issues with rigidity which you need for any kind of metal milling.

A controllable spindle would be nice nevertheless so if you (and others) are willing to invest in this go for it. Look for something that can be easily adapted to our controller board and don't expect it to help much with cutting aluminium.

**Comment by NitramLegov** [comment]
@Johannes09 mentioned that this would be a good enhancement, which could lead to more professional results as well as a longer lifetime of our bits.

If somebody is willing to work on this, here´s a small task list:
- [ ] Find a spindle which can be controlled (e.g. by PWM)
- [ ] Find a fitting controller board
- [ ] Ensure funding (e.g. through donations) and buy the mentioned hardware
- [ ] Test the controller board and the spindle with cncjs (should work)
- [ ] Assemble everything
- [ ] Adjust the CNC Router introduction (including the changes to the CAM Workflow)

**Comment by Chris0812** [comment]
Thanks for the bullet points :) 
Maybe now I can also contribute some more productive things to the project

**Comment by kenomaerz** [comment]
Falls es hier Bedarfe gibt, die wir sinnvoll als Spende formulieren können: Bitte hier die benötigten Bauteile und deren Preis listen und mich verlinken. Neue Werkzeuge können wir über betterplace.org als Spende durch Mitglieder finanzieren.

**Comment by lulebe** [comment]
So for 100€ I think anything above 500W is ruled out, 1.5kw spindles, even the cheap Chinese ones, including a vfd, go for at least 200€, probably closer to 300€.

These usually need a 0-10v analog input for speed control, which can rather easily be built with some passive components and then be connected to a 5v pwm output on grbl boards.

The 500W spindle doesn't seem to great to me as it's lower power, despite possibly having higher torque and definitely lower rpm. So maybe a 1.5kw option is better despite being more expensive.

PS: Sorry for just posting here, I'm hoping for everything to calm down and then join you guys, so I thought I'd give my thoughts on this since I just had the same decision to make on my own router.

**Comment by LukasFreeze** [comment]
Haha nothing to be sorry about, it's great to see "outsiders" actually find
us here and care to contribute - thank you :-D

Looking forward to meeting you whenever it is possible again!

**Comment by NitramLegov** [comment]
In the meantime, we have got the new Kress CNC, which can be used to kill aluminum :-)

For woodworking, I think controlling the speed of the bit with the speed selection on the router itself should be enough.

Therefore, I am closing this issue.
