### ISSUE TITLE
CNC router Raspi down

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#88]
The Raspi of the CNC router doesn't boot anymore. It seems like the SD card is broken/corrupted and needs a fresh install.

* [x] make a fresh raspbian and install cncjs on it.

**Comment by NitramLegov** [comment]
This should be a quick fix.  Just follow the instructions in the readme of the GcodeSender Repository:
https://github.com/comakingspace/GcodeSender
The install skript in there should automatically download our cncjs fork, compile it and then install it as a service.

Do we have SD-Cards available?

**Comment by Pakue95** [comment]
I have installed the CNCjs fork on a new SD card, but the webinterface is not reachable on port 8080. SSH works though.

**Comment by NitramLegov** [comment]
CNCjs should be up and running again.

@Narquadah manually executed the install_cncjs_custom.sh script, which installed cncjs properly
What still needs to be checked is why the overall script didn´t execute properly.
Ideas:
- Script could be broken
- Script might have needed more time and was aborted too early

**Comment by Pakue95** [comment]
Did you have a chance to test the script again?

**Comment by LukasFreeze** [comment]
> Did you have a chance to test the script again?

How about now? ;-)

**Comment by NitramLegov** [comment]
Not yet, sorry!
I´m planning to do it soon though :D
Especially since I would like to adjust our fork in order to get the latest cncjs upgrades

**Comment by NitramLegov** [comment]
Since we recognized lately that the default workspace settings (#57) seem to be broken, this has got a new priority.
I´ll propose the following tasklist:

- [ ] Check if we can find out what broke #57 (assumption: did somebody hit the update button?)
- [ ] Disable the update button
- [x] Update our fork to the lastest master of cncjs
- [ ] recompile the fork on a regular Computer and check the changes
- [ ] Change the Installation script (https://github.com/comakingspace/GcodeSender/blob/master/install.sh) to include cnc-panel
- [ ] Run the script on a pi and test it with that
- [ ] Put the upgraded pi to the router

**Comment by NitramLegov** [comment]
As part of #117 I ran the script on an additional raspberry pi. It did run into a couple of errors, but these did not stop it from working overall.

All I did was following the instructions mentioned in the readme.

**Comment by NitramLegov** [comment]
Ich habe das Skript jetzt nochmal ausgeführt und hatte dieses mal die gleichen Probleme wie Patrick.
Als ich das install.sh nochmal direkt ausgeführt habe hat es funktioniert.

Die Readme ist angepasst, der Pi für die CNC Fräse ist auf der neuen Version, ich mach hier entsprechend mal zu
