### ISSUE TITLE
Add a network switch

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#90]
Unfortunately, our Router in the CommonRoom is running out of network ports.

If we want to add any further devices or rooms (such as the electronics room), we need to add a switch.

There is already a switch available which is currently located in the shelve next to the router. Unfortunately, it is missing a power supply. It needs a 5V / 1A power supply.

Once we have this, we can hang up the switch.

**Comment by LukasFreeze** [comment]
I just found such a power supply this weekend and will try it out on
Wednesday!

On Jan 7, 2019 1:29 AM, "NitramLegov" <notifications@github.com> wrote:

Unfortunately, our Router in the CommonRoom is running out of network ports.

If we want to add any further devices or rooms (such as the electronics
room), we need to add a switch.

There is already a switch available which is currently located in the
shelve next to the router. Unfortunately, it is missing a power supply. It
needs a 5V / 1A power supply.

Once we have this, we can hang up the switch.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/comakingspace/do-something/issues/90>, or mute the
thread

**Comment by LukasFreeze** [comment]
Seems to work :-)

actual network test to be done by whoever wants to add more devices...

**Comment by NitramLegov** [comment]
Done
